import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import Card from "../components/Card";
import Link from "next/link";
import { PageNotFoundError } from "next/dist/shared/lib/utils";
export default function Posts() {
  const [posts, setPosts] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  useEffect(() => {
    const startingValue = currentPage === 1 ? 0 : currentPage * 10 - 10;
    axios.get(`api/getPosts/${startingValue}`).then((response) => {
      setPosts(response.data);
    });
  }, [currentPage]);
  let pageNumbers = [];
  for (let i = 1; i <= 10; i++) {
    pageNumbers.push(i);
  }
  const handlePageChange = (pageNumber) => {
    setCurrentPage(pageNumber);
    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  };
  return (
    <div className="main-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Link href="/">
        <a>Back</a>
      </Link>
      {posts &&
        posts.map((post) => (
          <Card id={post.id} title={post.title} body={post.body} />
        ))}
      <div className="page-numbers">
        {pageNumbers.map((page) => (
          <span
            onClick={() => handlePageChange(page)}
            className={`page-number ${page === currentPage ? "current" : ""}`}
          >
            {page}
          </span>
        ))}
      </div>
    </div>
  );
}
